name: Build

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: snapshot
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false
        gradle-home-cache-cleanup: true
    - name: Build
      run: ./gradlew build